In [1]:
import numpy

In [2]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 15, 17, 19, 23, 29, 31])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 15, 17, 19, 23, 29, 31])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(12,)

In [6]:
array2 = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [7]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
type(array2)

numpy.ndarray

In [9]:
array2.shape

(3, 4)

In [10]:
array1.size

12

In [11]:
array2.size

12

In [12]:
import numpy as np

In [13]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [14]:
array1[[1, 3, 4]]

array([ 3,  7, 11])

In [15]:
array2 = np.array([2, 1, 3])

In [16]:
array1[array2]

array([5, 3, 7])

In [17]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [18]:
array1[[1]]

array([3])

In [19]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [20]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [24]:
array1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
array1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [28]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [29]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [30]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [31]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [32]:
np.where(array1 % 2 ==0)

(array([0]),)

In [33]:
np.where(array1 > 4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)

In [34]:
filter = np.where(array1 > 4)

In [36]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])