In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])

A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [3]:
B = np.array([
    [0, 1],
    [-1, 3],
    [5, 2]
])

B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [5]:
C = np.random.rand(3, 5)
C

array([[0.95772024, 0.31949136, 0.45847988, 0.46055775, 0.40927377],
       [0.43792436, 0.5258555 , 0.15864137, 0.83664897, 0.3134761 ],
       [0.67207104, 0.32816291, 0.38405848, 0.72474337, 0.76958847]])

In [7]:
D = np.zeros((2, 4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [9]:
A[0][2]

2

In [10]:
## matrix calculation

A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

B = np.random.rand(3, 3)

In [11]:
B

array([[0.96700942, 0.44981004, 0.88931458],
       [0.90689889, 0.76285036, 0.2991018 ],
       [0.07353253, 0.75979223, 0.50198606]])

In [16]:
A + B

array([[ 1.96700942, -0.55018996,  2.88931458],
       [ 3.90689889,  2.76285036,  2.2991018 ],
       [ 4.07353253,  1.75979223,  2.50198606]])

In [17]:
5 * A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [15]:
np.dot(A, B)

array([[0.2071756 , 1.20654415, 1.5941849 ],
       [4.86189113, 4.39471532, 4.27011944],
       [4.92200166, 4.081675  , 4.86033222]])

In [18]:
A @ B

array([[0.2071756 , 1.20654415, 1.5941849 ],
       [4.86189113, 4.39471532, 4.27011944],
       [4.92200166, 4.081675  , 4.86033222]])

In [19]:
A @ B + (A + 2 * B)

array([[3.14119445, 1.10616423, 5.37281405],
       [9.67568891, 7.92041605, 6.86832303],
       [9.06906673, 6.60125947, 7.86430434]])

In [20]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [21]:
A_transpose = np.transpose(A)
A_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [22]:
A_transpose = A.T
A_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [23]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
A @ I

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [26]:
A_inverse = np.linalg.pinv(A)  ## if there is no inverse, return matrix close to inverse
A_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [27]:
A @ A_inverse

array([[ 1.00000000e+00,  7.77156117e-16, -8.88178420e-16],
       [ 0.00000000e+00,  1.00000000e+00, -8.88178420e-16],
       [ 0.00000000e+00,  4.44089210e-16,  1.00000000e+00]])