In [2]:
import numpy as np

In [3]:
## matrix arithmetic operation practice

A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, 2, 3, 1],
    [3, 1, 4, 3, 1],
])

B = np.array([
    [1, 1, 1, 1, 1],
    [2, 2, 2, 2, 2],
    [3, 3, 3, 3, 3],
    [4, 4, 4, 4, 4],
])

In [4]:
A + B  ## summation

array([[4, 4, 3, 4, 2],
       [7, 4, 4, 5, 3],
       [6, 6, 5, 6, 4],
       [7, 5, 8, 7, 5]])

In [5]:
A - B  ## diff

array([[ 2,  2,  1,  2,  0],
       [ 3,  0,  0,  1, -1],
       [ 0,  0, -1,  0, -2],
       [-1, -3,  0, -1, -3]])

In [6]:
A * B  ## multiplication by element

array([[ 3,  3,  2,  3,  1],
       [10,  4,  4,  6,  2],
       [ 9,  9,  6,  9,  3],
       [12,  4, 16, 12,  4]])

In [7]:
A / B  ## division by element

array([[3.        , 3.        , 2.        , 3.        , 1.        ],
       [2.5       , 1.        , 1.        , 1.5       , 0.5       ],
       [1.        , 1.        , 0.66666667, 1.        , 0.33333333],
       [0.75      , 0.25      , 1.        , 0.75      , 0.25      ]])

In [8]:
## nan

A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, np.nan, 3, 1],
    [3, 1, 4, 3, 1],
])

B = np.array([
    [1, np.nan, 1, 1, 1],
    [2, 2, 2, 2, 2],
    [3, 3, 3, 3, 3],
    [np.nan, 4, 4, 4, 4],
])

In [9]:
## if nan is in either matrix, result is nan
A + B

array([[ 4., nan,  3.,  4.,  2.],
       [ 7.,  4.,  4.,  5.,  3.],
       [ 6.,  6., nan,  6.,  4.],
       [nan,  5.,  8.,  7.,  5.]])

In [10]:
## scala multiplication
A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, 2, 3, 1],
    [3, 1, 4, 3, 1],
])

5 * A

array([[15, 15, 10, 15,  5],
       [25, 10, 10, 15,  5],
       [15, 15, 10, 15,  5],
       [15,  5, 20, 15,  5]])

In [11]:
## matrix multiplication

A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, 2, 3, 1],
    [3, 1, 4, 3, 1],
])

B = np.array([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])

A @ B

array([[12, 24, 36, 48, 60],
       [13, 26, 39, 52, 65],
       [12, 24, 36, 48, 60],
       [12, 24, 36, 48, 60]])

In [12]:
## matrix indexing

In [16]:
## access row of matrix
A = np.array([
    [3, 3, 2, 3, 1],
    [5, 2, 2, 3, 1],
    [3, 3, 2, 3, 1],
    [3, 1, 4, 3, 1],
])

print(A[0])  ## 0행
print(A[3])  ## 3행
print(A[0][3])  ## 0행 3열
print(A[1][1])  ## 1행 1열
print(A[:, 3])  ## 3열
print(A[3, :])  ## 3행

[3 3 2 3 1]
[3 1 4 3 1]
3
2
[3 3 3 3]
[3 1 4 3 1]
